backend:
  name: github
  repo: digitalkode/digitalkode
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://www.digitalkode.com
  auth_endpoint: netlify-login/auth
  site_domain: https://www.digitalkode.com
  open_authoring: true
  commit_messages:
    create: Create {{collection}} "{{slug}}"
    update: Update {{collection}} "{{slug}}"
    delete: Delete {{collection}} "{{slug}}"
    uploadMedia: Upload "{{path}}"
    deleteMedia: Delete "{{path}}"
publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
site_url: https://www.digitalkode.com

collections:
  - name: Authors
    label: Authors
    identifier_field: authors
    folder: "content/authors" # The path to the folder where the documents are stored
    path: "{{slug}}/_index"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - label: Social Media
        name: social
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Link, name: url, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: blog
    label: "Blog"
    identifier_field: blog
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "authors", widget: "list"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: HTML
    label: "HTML"
    identifier_field: HTML
    folder: "content/html"
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "authors", widget: "list"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: PHP
    label: "PHP"
    identifier_field: PHP
    folder: "content/php"
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "authors", widget: "list"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
